name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # 1) Checkout (v4)
      # -----------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------
      # 2) JDK 설정 (Java 17)
      # -----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # -----------------------------
      # 3) gradlew 실행가능하게 만들기
      # -----------------------------
      - name: Make gradlew executable
        run: |
          ls -al
          chmod +x ./gradlew

      # -----------------------------
      # 4) 빌드 실행
      # -----------------------------
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # -----------------------------
      # 5) 빌드 결과물 업로드
      # -----------------------------
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
